builders:
  featureBuilder:
    import: "package:bdd_widget_test/bdd_widget_test.dart"
    builder_factories: ["featureBuilder"]
    build_extensions: {".feature": [".feature.g.dart"]}
    build_to: source
    auto_apply: root_package
